### ISSUE TITLE
Missing format string specifier

### ISSUE THREAD

**Issue by UnknownError55** [rom1504/embedding-reader#32]
The line `raise ValueError("No embeddings found in folder {embeddings_folder}")` in [line 49 of parquet_numpy_reader.py](https://github.com/rom1504/embedding-reader/blob/main/embedding_reader/parquet_numpy_reader.py#L49) is missing the format string specifier, thus printing out the format string syntax instead of performing a format string replacement.

**Comment by rom1504** [comment]
fixed
