### ISSUE TITLE
How do you prepare the local dataset?

### ISSUE THREAD

**Issue by zhenzi0322** [rom1504/embedding-reader#35]
I want to prepare a dataset similar to the one in the link below

https://mystic.the-eye.eu/public/AI/cah/laion5b/embeddings/laion2B-en/

`img_emb_0005.npy`：
```.npy
�NUMPY v {'descr': '<f2', 'fortran_order': False, 'shape': (938705, 768), } 
````
What does 938705 stand for?
What does 768 stand for?

**Comment by rom1504** [comment]
938705 is the number of rows
768 is the dimension of the embeddings

you can use numpy to save embeddings

**Comment by zhenzi0322** [comment]
> 938705 is the number of rows 768 is the dimension of the embeddings
> 
> you can use numpy to save embeddings

```
clip-retrieval inference --input_dataset image_folder --output_folder embeddings_folder
```


How can the above command not convert the. npy file

**Comment by rom1504** [comment]
Check clip-retrieval readme, feel free to open an issue there
