### ISSUE TITLE
[question] Multiple vs single parquet/np files for embeddings

### ISSUE THREAD

**Issue by apsdehal** [rom1504/embedding-reader#38]
In practice, when we are processing embeddings at billion scale, does it matter if we have multiple parquet/np files vs single?

[This](https://stackoverflow.com/questions/56273277/optimal-file-size-and-parquet-block-size) SO link has some good comments, but I wanted to get your opinion.

**Comment by rom1504** [comment]
it depends on your file system. If it supports range requests then this is equivalent as you can get in parallel multiple pieces of a single file.
For parquet file, it's less true as you can only split at the border of groups
