### ISSUE TITLE
Would there be a way to allow for more recent pyarrow versions?

### ISSUE THREAD

**Issue by gietema** [rom1504/embedding-reader#39]
Hi, would there be a way to allow more recent pyarrow versions?
The current `pyarrow>=6.0.1,<8` requirements means we're stuck with a version from 2017, and makes it difficult to install libraries that require more recent versions. Is there a specific reason this library uses `pyarrow>=6.0.1,<8`. 

I'm happy to contribute to any implementation changes if needed.

**Comment by victor-paltz** [comment]
Hello!
Yes it is possible, this PR will loosen the constraints: https://github.com/rom1504/embedding-reader/pull/40
I don't see any specific reason why it was pined to <8 max, maybe because it was the last available version for python3.6?

**Comment by rom1504** [comment]
yes, depending on a single major version range is a good pattern if packages are following semver. That way users get new minor and patch versions of deps that may improve things ; but they don't get major versions that may break the package.

**Comment by rom1504** [comment]
done
