### ISSUE TITLE
EmbeddingReader.__init__() got an unexpected keyword argument 'metadata_folder'

### ISSUE THREAD

**Issue by segalinc** [rom1504/embedding-reader#43]
Hello, 

I am trying to use the library to read some embeddings but I get this error

here how to reproduce 

```
from embedding_reader import EmbeddingReader

embedding_reader = EmbeddingReader(embeddings_folder="https://mystic.the-eye.eu/public/AI/cah/laion5b/embeddings/laion2B-en/img_emb/",
                                   metadata_folder="https://mystic.the-eye.eu/public/AI/cah/laion5b/embeddings/laion2B-en/laion2B-en-metadata/", 
                                   file_format="parquet_npy",    
                                   meta_columns=["url", "caption"],
)

print("embedding count", embedding_reader.count)
print("dimension", embedding_reader.dimension)
print("total size", embedding_reader.total_size)
print("byte per item", embedding_reader.byte_per_item)

for emb, meta in embedding_reader(batch_size=10 ** 6, start=0, end=embedding_reader.count, max_ram_usage_in_bytes=2**30):
    print(emb.shape)
    print(meta["url"], meta["caption"])
    break
 ```

Error :
`TypeError: EmbeddingReader.__init__() got an unexpected keyword argument 'metadata_folder'`

**Comment by rom1504** [comment]
that's unexpected... what version of the lib are you using?

**Comment by segalinc** [comment]
It's 1.1.7

**Comment by segalinc** [comment]
also what if I want to read both text and img emebdding? is is possible to achieve this in one reader?

**Comment by segalinc** [comment]
ok I guess it worked even tho I am gettin another error that it doesn't find the embedding folder now

**Comment by rom1504** [comment]
This is quite surprising

Can you say more about your environment? Python version, operating system, venv,...

**Comment by rom1504** [comment]
About reading image and text embedding, you can make 2 instance of the reader and then use zip to combine the iterators

**Comment by rom1504** [comment]
Laion2B provided image embeddings are clip image embeddings
