### ISSUE TITLE
Is the content of embedding_folder always npy, but why is the shape of npy files two-dimensional while the image is three-dimensional

### ISSUE THREAD

**Issue by chuanyueaiqing** [rom1504/embedding-reader#68]
Is the content of embedding_folder always npy, but why is the shape of npy files two-dimensional while the image is three-dimensional

**Comment by rom1504** [comment]
Embedding reader does not manipulate images.

**Comment by chuanyueaiqing** [comment]
So what should we read?

**Comment by chuanyueaiqing** [comment]
Or how should I transform the image data to be read and loaded

**Comment by rom1504** [comment]
What are you trying to do ?

Embedding reader is a package to read embeddings 

Do you want to read embeddings ?

**Comment by chuanyueaiqing** [comment]
I'm very sorry, as I am reading a code article for Dalle2 that uses your code for data source iteration. I would like to try the code for Dalle2, but because its data source uses your function, I don't know how to create the data source.
